sudo: required
services:
  - docker

before_install:
  - docker build -t danielcortes/docker-react -f Dockerfile.dev .

script:
  - docker run danielcortes/docker-react npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-809781640685"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
      